### ISSUE TITLE
Blocking world from loading

### ISSUE THREAD

**Issue by SettingDust** [alcatrazEscapee/cyanide#23]
Is blocking world from loading as expected? It's won't blocking by the error without this mod. 
```
[23:16:10] [Render thread/WARN] (Minecraft) Failed to load level data or datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Error(s) loading registries:


Errors(s) loading registry minecraft:worldgen/biome:

Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / minecraft:music.overworld.jungle_and_forest]
	at: "effects"
	at: worldgen/biome 'profundis:worldgen/biome/amethyst_caves.json'
	at: pack 'fabric'


Errors occurred freezing registries.
These were elements that were referenced, but never defined (or their definition had an error above).

Missing references from the worldgen/biome registry: [
	'profundis:amethyst_caves'
]


	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41891(class_7196.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:407) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.moulberry.axiom.editor.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:190) ~[Axiom-1.5.1-for-MC1.20.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Error(s) loading registries:


Errors(s) loading registry minecraft:worldgen/biome:

Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / minecraft:music.overworld.jungle_and_forest]
	at: "effects"
	at: worldgen/biome 'profundis:worldgen/biome/amethyst_caves.json'
	at: pack 'fabric'


Errors occurred freezing registries.
These were elements that were referenced, but never defined (or their definition had an error above).

Missing references from the worldgen/biome registry: [
	'profundis:amethyst_caves'
]


	at com.alcatrazescapee.cyanide.codec.MixinHooks.loadAllRegistryData(MixinHooks.java:137) ~[cyanide-fabric-1.20-4.0.0.jar:?]
	at net.minecraft.class_7655.handler$eih000$cyanide$loadAndReportErrors(class_7655.java:1519) ~[client-intermediary.jar:?]
	at net.minecraft.class_7655.method_45121(class_7655.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_45142(class_7237.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_45143(class_7237.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:187) ~[client-intermediary.jar:?]
	... 29 more
```

**Comment by alcatrazEscapee** [comment]
Cyanide detects errors. This is an error in the mod, they specify a music which is invalid, but vanilla just ignores it. Cyanide promotes some optional field errors to real errors instead of silently accepting them. I have gone ahead and reported this issue to the mod in question:

https://github.com/firenh/Profundis/issues/19
