### ISSUE TITLE
When there is a few types of biomes atempted to be generated and the player is rendering it, it crashes the server

### ISSUE THREAD

**Issue by heyxmirko** [alcatrazEscapee/cyanide#25]
```---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-11-21 21:45:19
Description: Exception generating new chunk

com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 10
Feature 'cyclic:flower_purple'
  must be before 'cyclic:flower_absalon' (defined in 'terralith:forested_highlands' at index 1, 2 and 5 others)
  must be before 'cyclic:flower_cyan' (defined in 'terralith:forested_highlands' at index 2, 3 and 16 others)
  must be before 'cyclic:flower_purple' (defined in 'minecraft:snowy_beach' at index 1, 2 and 1 others)

	at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141) ~[cyanide-forge-1.20.1-4.1.0.jar%23176!/:4.1.0] {re:mixin,re:classloading}
	at net.minecraft.world.level.biome.FeatureSorter.handler$zzk000$buildFeaturesPerStepWithAdvancedCycleDetection(FeatureSorter.java:529) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,re:classloading,pl:mixin:APP:cyanide.common.mixins.json:FeatureSorterMixin,pl:mixin:A}
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,re:classloading,pl:mixin:APP:cyanide.common.mixins.json:FeatureSorterMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223094_(ChunkGenerator.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%2374!/:?] {}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:288) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Cyanide (cyanide), Version: 4.1.0
		Issue tracker URL: https://github.com/alcatrazEscapee/cyanide/issues
		at TRANSFORMER/cyanide@4.1.0/com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141)
Stacktrace:
	at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141) ~[cyanide-forge-1.20.1-4.1.0.jar%23176!/:4.1.0] {re:mixin,re:classloading}
	at net.minecraft.world.level.biome.FeatureSorter.handler$zzk000$buildFeaturesPerStepWithAdvancedCycleDetection(FeatureSorter.java:529) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,re:classloading,pl:mixin:APP:cyanide.common.mixins.json:FeatureSorterMixin,pl:mixin:A}
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,re:classloading,pl:mixin:APP:cyanide.common.mixins.json:FeatureSorterMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223094_(ChunkGenerator.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%2374!/:?] {}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:288) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
-- Chunk to be generated --
Details:
	Location: 116,285
	Position hash: 1224065679476
	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@2499ffe
Stacktrace:
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['keat6'/63, l='ServerLevel[New World]', x=2019.44, y=103.00, z=4403.29]]
	Chunk stats: 4058
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,84,0), Section: (at 0,4,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5338852 game time, 5276917 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 53860 (now: false), thunder time: 156436 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-57-generic
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1837158712 bytes (1752 MiB) / 3690987520 bytes (3520 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 85 Stepping 4
	Microarchitecture: Skylake (Server)
	Frequency (GHz): 3.20
	Number of physical packages: 2
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 177953.16
	Virtual memory used (MB): 252285.09
	Swap memory total (MB): 49151.99
	Swap memory used (MB): 16220.37
	JVM Flags: 3 total; -Xmx6144M -Xms512M -Xss2M
	Server Running: true
	Player Count: 1 / 2; [ServerPlayer['keat6'/63, l='ServerLevel[New World]', x=2019.44, y=103.00, z=4403.29]]
	Data Packs: vanilla, mod:w2w2 (incompatible), mod:lucky (incompatible), mod:handcrafted (incompatible), mod:amplifiednether, mod:notenoughcrashes (incompatible), mod:ironfurnaces, mod:beautify (incompatible), mod:jei, mod:iceberg (incompatible), mod:xaerominimap, mod:waystones, mod:croptopia (incompatible), mod:structory, mod:xaeroworldmap, mod:cookingforblockheads, mod:prism (incompatible), mod:travelersbackpack, mod:resourcefullib (incompatible), mod:coroutil (incompatible), mod:architectury (incompatible), mod:balm, mod:terralith, mod:jeresources, mod:cloth_config (incompatible), mod:forge, mod:ctov, mod:earthtojavamobs (incompatible), mod:athena, mod:betterfoliage (incompatible), mod:chipped (incompatible), mod:treeharvester, mod:collective, mod:old_combat_mod (incompatible), mod:forgeconfigscreens, mod:betterfpsdist (incompatible), mod:cupboard (incompatible), mod:infinitetrading, mod:gravestone, mod:naturescompass, mod:embeddium, mod:simpleplanes (incompatible), mod:cfm, mod:twilightforest, mod:curios (incompatible), mod:fastload, mod:clumps (incompatible), mod:spawnermod (incompatible), mod:darktimer, mod:ironchest, mod:flib, mod:cyclic, file/Drafts.zip (incompatible), mod:biome_replacer, mod:cyanide (incompatible), file/Purple flower fix
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.6.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.6.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.6.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.6.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.6.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar serializationisbad TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		notenoughcrashes-4.4.6+1.20.1-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.4.6+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Fastload-Reforged-mc1.20.1-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		beautify-2.0.2.jar                                |Beautify                      |beautify                      |2.0.2               |DONE      |Manifest: NOSIGNATURE
		treeharvester-1.20.1-8.3.jar                      |Tree Harvester                |treeharvester                 |8.3                 |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		OldCombatMod_1.20.X.jar                           |Old Combat Mod                |old_combat_mod                |1.1                 |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.2.jar                   |Waystones                     |waystones                     |14.0.2              |DONE      |Manifest: NOSIGNATURE
		Structory_1.20.2_v1.3.3.jar                       |Structory                     |structory                     |1.3.3               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.36.0_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.36.0              |DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.20-16.0.1.jar        |CookingForBlockheads          |cookingforblockheads          |16.0.1              |DONE      |Manifest: NOSIGNATURE
		Prism-1.20.1-forge-1.0.5.jar                      |Prism                         |prism                         |1.0.5               |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.20.1-9.1.11.jar               |Traveler's Backpack           |travelersbackpack             |9.1.11              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		spawnermod-1.20.1-1.9.3+Forge.jar                 |Enhanced Mob Spawners         |spawnermod                    |1.9.3               |DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.20.1-5.2.4.jar                     |Simple Planes                 |simpleplanes                  |1.20.1-5.2.4        |DONE      |Manifest: NOSIGNATURE
		cyanide-forge-1.20.1-4.1.0.jar                    |Cyanide                       |cyanide                       |4.1.0               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |DONE      |Manifest: NOSIGNATURE
		Terralith_1.20.2_v2.4.8 (1).jar                   |Terralith                     |terralith                     |2.4.8               |DONE      |Manifest: NOSIGNATURE
		darktimer-forge-1.20.1-1.0.6.jar                  |DarkTimer - Clear Entity Lag  |darktimer                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.238.jar          |Just Enough Resources         |jeresources                   |1.4.0.238           |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.6-universal.jar                 |Forge                         |forge                         |47.2.6              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ctov-3.3.6.jar                                    |ChoiceTheorem's Overhauled Vil|ctov                          |3.3.6               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.1893-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1893            |DONE      |Manifest: NOSIGNATURE
		biome_replacer-1.2-forge.jar                      |Biome Replacer                |biome_replacer                |1.2                 |DONE      |Manifest: NOSIGNATURE
		embeddium-0.2.9+mc1.20.1.jar                      |Embeddium                     |embeddium                     |0.2.9+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.1.1.jar                     |Athena                        |athena                        |3.1.1               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4.jar                       |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |DONE      |Manifest: NOSIGNATURE
		chipped-forge-1.20.1-3.0.1.jar                    |Chipped                       |chipped                       |3.0.1               |DONE      |Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		xaeros_waystones_compability-1.0.jar              |Xaero's Map - Waystones Compab|w2w2                          |1.0                 |DONE      |Manifest: NOSIGNATURE
		lucky-block-forge-1.20.1-13.0.jar                 |Lucky Block                   |lucky                         |1.20.1-13.0         |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.20.1-3.0.5.jar                |Handcrafted                   |handcrafted                   |3.0.5               |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_1.20.2_v1.2.3.jar                |Amplified Nether              |amplifiednether               |1.2.3               |DONE      |Manifest: NOSIGNATURE
		ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar        |Forge Config Screens          |forgeconfigscreens            |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		ironfurnaces-1.20.1-4.1.3.jar                     |Iron Furnaces                 |ironfurnaces                  |4.1.3               |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.20.1-4.0.jar                      |betterfpsdist mod             |betterfpsdist                 |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.20.1-forge-1.1.16.jar                   |Iceberg                       |iceberg                       |1.1.16              |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.4.2+1.20.1.jar                     |Curios API                    |curios                        |5.4.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.8.4_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.8.4              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.20.1-1.0.5.jar                       |Gravestone Mod                |gravestone                    |1.20.1-1.0.5        |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.20.1-FORGE-2.3.2.jar                  |Croptopia                     |croptopia                     |2.3.2               |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-7.7.jar                         |Collective                    |collective                    |7.7                 |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.16.jar            |Resourceful Lib               |resourcefullib                |2.1.16              |DONE      |Manifest: NOSIGNATURE
		coroutil-1.20.1-1.3.0.jar                         |CoroUtil                      |coroutil                      |1.20.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.1.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.1          |DONE      |Manifest: NOSIGNATURE
		flib-1.20.1-0.0.11.jar                            |flib                          |flib                          |0.0.11              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		infinitetrading-1.20.1-4.1.jar                    |Infinite Trading              |infinitetrading               |4.1                 |DONE      |Manifest: NOSIGNATURE
		earth2java-forge-1.10.1+1.20.1.jar                |Earth2Java                    |earthtojavamobs               |1.10.1              |DONE      |Manifest: NOSIGNATURE
		betterfoliage-5.0.1.jar                           |Better Foliage                |betterfoliage                 |5.0.1               |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.20.1-1.12.4 (1).jar                      |Cyclic                        |cyclic                        |1.12.4              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: 4e00ad0c-7124-4b4d-a15b-e1dc2dbaa4ad
	FML: 47.2
	Forge: net.minecraftforge:47.2.6
	Suspected Mods: Cyanide (cyanide), Minecraft (minecraft)```

**Comment by alcatrazEscapee** [comment]
This error is not an issue with Cyanide; rather, Cyanide is correctly identifying an incompatibility between Terralith and Cyclic. This would have still crashed without cyanide, just with an unhelpful error. I suggest you report this to both Terralith and Cyclic.
