### ISSUE TITLE
Incompatible with Quilted Fabric API

### ISSUE THREAD

**Issue by SalmonSnakeD** [alcatrazEscapee/cyanide#27]
**I launched my game with a minimal set of just 37 mods (Quilt 1.20.1 v0.24.0) and put Cyanide into that modpack, and when I try to join a world, it instantly crashes with the stack trace below:**

```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at org.quiltmc.qsl.worldgen.biome.impl.TheEndBiomeData.getAddedBiomes(TheEndBiomeData.java:101)
	at org.quiltmc.qsl.worldgen.biome.impl.TheEndBiomeData$Overrides.<init>(TheEndBiomeData.java:132)
	at org.quiltmc.qsl.worldgen.biome.impl.TheEndBiomeData.createOverrides(TheEndBiomeData.java:97)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2169.method_28443(class_2169.java:590)
	at net.minecraft.class_7869.method_46706(class_7869.java:79)
	at net.minecraft.class_7869.method_46699(class_7869.java:66)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at net.minecraft.class_7869.method_46702(class_7869.java:67)
	at net.minecraft.class_2794.method_46696(class_2794.java:108)
	at net.minecraft.class_3898.<init>(class_3898.java:190)
	at net.minecraft.class_3215.<init>(class_3215.java:87)
	at net.minecraft.class_3218.<init>(class_3218.java:231)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:399)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)
```
# Modlist:
 - Client side noteblocks
 - Boat break fix
 - Chunksending Mod (Not available on Modrinth)
 - Cloth Config API
 - Concurrent chunk management engine
 - Cyanide
 - Dashloader
 - Debugify
 - Enhanced block entities
 - Entity culling
 - Fast anim
 - Fast chest (Not available on Modrinth)
 - Fast quit
 - Faster random
 - FerriteCore
 - Idle tweaks
 - ImmediatelyFast
 - Krypton
 - LanguageReload
 - LazyDFU
 - Lithium
 - Logical zoom
 - MemoryLeakFix
 - Methane
 - Mod menu
 - Modernfix
 - Moreculling
 - Nvidium
 - QFAPI
 - Reese's sodium options
 - Server pinger fixer
 - Shared resources
 - Smoothchunk mod (Not available on Modrinth)
 - Sodium
 - Sodium Extra
 - ThreadTweak
 - Cupboard (Not available on Modrinth)

> Detailed mod list with mod versions, filenames, and library mods not located in the regular mods folder can be found here: https://pastebin.com/1AB6z36S (The text formatting is messed up, sorry.)

I created a profile (Quilt 1.20.1 v0.24.0) where I have only Cyanide installed to the profile, and my game did not crash when I joined a world.

**Comment by alcatrazEscapee** [comment]
Cyanide is not tested against, not developed for, and does not support quilt. It is not marked on any platform as supporting quilt.

**Comment by SalmonSnakeD** [comment]
Cyanide is compatible with the Quilt modloader.

> In the original message I said: "I created a profile (Quilt 1.20.1 v0.24.0) where I have only Cyanide installed to the profile, and my game did **not** crash when I joined a world."

So the issue is in one of the mods I listed above, and after a little troubleshooting the mod that's incompatible ended up being QFAPI https://modrinth.com/mod/qsl

So like I expected, this mod does in fact work with the Quilt modloader itself, like almost all of the Fabric mods do anyway. 
But the Quilt libraries mod seems to have problems with something this mod does.

So do you have any plans on making this mod compatible with QFAPI?
